@startuml
hide empty description
state GasPump {
[*] --> S1: insertCard
S1 --> S2: / requestPin
S2 --> S3: pinCode
S3 --> S4: / validate
S4 --> S5: result(pinOK)
state S5 {
[*] --> S7
S7 --> S9: pinOk
state S9 {
[*] --> S10: / startFuel
S10 --> [*]: hangUp
}
S9 --> [*]
S7 --> S12: !pinOk
state S12 {
[*] --> [*]: / invalidPin
}
S12 --> [*]
}
S5 --> [*]: / cardOut
}
@enduml
